# Configuring Cascade for system-wide use
# =======================================
#
# This configuration file is packaged with Cascade for system-wide setups (e.g.
# with systemd).  See 'config.template.toml' for a complete description of the
# settings and their defaults.

version = "v1"

policy-dir = "/etc/cascade/policies"
zone-state-dir = "/var/lib/cascade/zone-state"
tsig-store-path = "/var/lib/cascade/tsig-keys.db"
kmip-credentials-store-path = "/var/lib/cascade/kmip/credentials.db"
keys-dir = "/var/lib/cascade/keys"
kmip-server-state-dir = "/var/lib/cascade/kmip"
dnst-binary-path = "/usr/libexec/cascade/cascade-dnst"

[daemon]
log-level = "info"
log-target = { type = "syslog" }
daemonize = false

[remote-control]
servers = ["127.0.0.1:4539", "[::1]:4539"]

[loader]
review.servers = ["127.0.0.1:4540", "[::1]:4540"]

[signer]
review.servers = ["127.0.0.1:4541", "[::1]:4541"]

[server]
servers = ["127.0.0.1:4542", "[::1]:4542"]
